### ISSUE TITLE
Preprocessing Operations

### ISSUE THREAD

**Issue by furkankaradas** [tzczsq/audio-visual-emotion-recognition-using-a-hybrid-deep-model#2]
Hi,
Thanks for greating work.
We have problem preprocessing operations. We don't obtain same segment both audio and visual parts, so can't perform fusion part. Can you explicate visual and audio parts (specially divided segments), also share with code for visual preprocessing?
Thank you, sincerely yours.

**Comment by tzczsq** [comment]
Hi, 
  Thanks for your interests.
  In my impression, it is easy to repeat or delete the frames in an audo or video segment parts so that they have the same length for fusion. More details can be found in our paper.
Best,
Dr. Shiqing Zhang











At 2020-02-04 13:33:22, "Furkan Karadaş" <notifications@github.com> wrote:

Hi,
Thanks for greating work.
We have problem preprocessing operations. We don't obtain same segment both audio and visual parts, so can't perform fusion part. Can you explicate visual and audio parts (specially divided segments), also share with code for visual preprocessing?
Thank you, sincerely yours.
